package com.domain.mapper;

import com.domain.po.TbSysUser;
import com.domain.po.TbSysUserExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface TbSysUserMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_sys_user
     *
     * @mbggenerated Wed Nov 06 18:10:11 CST 2019
     */
    int countByExample(TbSysUserExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_sys_user
     *
     * @mbggenerated Wed Nov 06 18:10:11 CST 2019
     */
    int deleteByExample(TbSysUserExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_sys_user
     *
     * @mbggenerated Wed Nov 06 18:10:11 CST 2019
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_sys_user
     *
     * @mbggenerated Wed Nov 06 18:10:11 CST 2019
     */
    int insert(TbSysUser record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_sys_user
     *
     * @mbggenerated Wed Nov 06 18:10:11 CST 2019
     */
    int insertSelective(TbSysUser record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_sys_user
     *
     * @mbggenerated Wed Nov 06 18:10:11 CST 2019
     */
    List<TbSysUser> selectByExample(TbSysUserExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_sys_user
     *
     * @mbggenerated Wed Nov 06 18:10:11 CST 2019
     */
    TbSysUser selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_sys_user
     *
     * @mbggenerated Wed Nov 06 18:10:11 CST 2019
     */
    int updateByExampleSelective(@Param("record") TbSysUser record, @Param("example") TbSysUserExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_sys_user
     *
     * @mbggenerated Wed Nov 06 18:10:11 CST 2019
     */
    int updateByExample(@Param("record") TbSysUser record, @Param("example") TbSysUserExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_sys_user
     *
     * @mbggenerated Wed Nov 06 18:10:11 CST 2019
     */
    int updateByPrimaryKeySelective(TbSysUser record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_sys_user
     *
     * @mbggenerated Wed Nov 06 18:10:11 CST 2019
     */
    int updateByPrimaryKey(TbSysUser record);
}